### PR TITLE
Msteams

### PR DESCRIPTION
**Pull request by agardnerIT**
Fix image paths

### CODE REVIEW

**Review by TannerGilbert — APPROVED** [review]
LGTM

**Comment by TannerGilbert** [comment]
It seems like the last commits introduced some conflicts inside the `README.md` and `artifacthub-pkg.yml`. Please take a look.

**Comment by agardnerIT** [comment]
@TannerGilbert I don't know how to solve this. Sorry. Any help is appreciated.

**Comment by TannerGilbert** [comment]
@agardnerIT You could solve this using the "Resolve conflicts" button on the PR itself:

image

But as I was looking through the merge conflict, I noticed that I actually solved the same thing in #129 because I didn't notice that you were already working on the broken images. Both PRs are currently still unmerged, so we can close one of them.

**Comment by agardnerIT** [comment]
Oh I saw that but glanced at the “only those with write access” warning and assumed I wouldn’t be able to do it. Oops. Anyway, closing this and you can merge your PR.

**Comment by TannerGilbert** [comment]
@agardnerIT Thanks. I will merge it as soon as it is reviewed.

**Pull request closed without merging**
