### PR TITLE
change owner from @Dynatrace-Adam-Gardner to @agardnerIT

### PR DESCRIPTION
**Pull request by agardnerIT**
This PR:

- Changes the ownership from @Dynatrace-Adam-Gardner to @agardnerIT

Doing this to standardise my commits.

Signed-off-by: agardnerit <adam@agardner.net>

### CODE REVIEW

**Comment by TannerGilbert** [comment]
@agardnerIT can you also take ownership of the other integrations you created?

**Comment by christian-kreuzberger-dtx** [comment]
image

**Review by StackScribe — APPROVED** [review]

**Review by TannerGilbert — APPROVED** [review]
Please wait with merging this until you have `writing` access so that the CODEOWNERS works as expected. Also please resolve the merge conflict from the Asana service.

**Comment by agardnerIT** [comment]
Please add @jainammm as he is owning the k6 integration due to the GSoC project

**Comment by christian-kreuzberger-dtx** [comment]
conflicts in codeowners

**Comment by TannerGilbert** [comment]
@agardnerIT I think this can be merged now as now that you have write access to the repository, all conflicts in the codeowners files for your account are resolved.

**Pull request merged**
